---
title: Urna Eletr√¥nica Virtual
timezone: America/Sao_Paulo
defaults:
-
  scope:
    type: pages
  values:
    layout: default
description: ""
baseurl: "/urna-eletronica"
url: http://copatecnologia.com.br
markdown: kramdown
permalink: ":preety/"
sass:
  style: compressed
exclude:
- node_modules
- desktop.ini
- gulpfile.js
- npm-debug.log
- package.json
